{% set name = "ldas-tools-al" %}
{% set version = "2.6.4" %}
{% set sha256 = "5507e4d8a2b2ff8855f9e427c51836b43b58d6471cf04ad844e93e17a84372a9" %}

# dependencies
{% set ldas_tools_cmake_version = "1.1.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-al", max_pin="x.x") }}
  ignore_run_exports:
    # not sure we need openssl, but the cmake configure demands it
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - openssl
  run_constrained:  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --print-errors --modversion ldastoolsal  # [unix]

about:
  home: "https://wiki.ligo.org/Computing/LDASTools"
  dev_url: "https://git.ligo.org/ldastools/LDAS_Tools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "LDAS tools abstraction toolkit"

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
