{% set name = "ldas-tools-al" %}
{% set version = "2.6.3" %}
{% set sha256 = "2ab6837b67960fd44756be212c71e4cc37981052b7129d9cd1c9f6e08cae7413" %}

# dependencies
{% set ldas_tools_cmake_version = "1.0.8" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    # not sure we need openssl, but the cmake configure demands it
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - openssl

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --print-errors --modversion ldastoolsal  # [unix]

about:
  home: "https://wiki.ligo.org/Computing/LDASTools"
  dev_url: "https://git.ligo.org/ldastools/LDAS_Tools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "LDAS tools abstraction toolkit"

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
