{% set name = "ldas-tools-al" %}
{% set version = "2.7.0" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 74abfe842d11e53e7e0b9adc846b6fe154e92a58e12200dfb5911312e8e8cc53
  patches:
    # https://git.ligo.org/computing/ldastools/LDAS_Tools/-/merge_requests/138
    - no-openssl.patch
    # don't build static libraries
    - no-static.patch
    # when cross-compiling without an emulator disable some checks that use try_run
    # see https://git.ligo.org/ldastools/LDAS_Tools/-/issues/117
    - no-check-procfs.patch  # [osx and arm64]

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-al", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - libboost-headers
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
  run_constrained:   # [osx and x86_64]

test:
  requires:
    - pkg-config
  commands:
    - test -f ${PREFIX}/lib/libldastoolsal${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/ldastoolsal/ldas_types.h  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} ldastoolsal

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
