{% set name = "ldas-tools-al" %}
{% set version = "2.6.1" %}
{% set sha256 = "cdb5e50eff88c9a64bc01677fc6540a91716966c165e29bdc7cd1e6fb6925619" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - swig
    - boost-cpp
    - openssl
  run:
    - zlib
    - openssl

test:
  commands:
    - test -f ${PREFIX}/include/ldastoolsal/ldas_types.h  # [not win]
    - test -f ${PREFIX}/lib/libldastoolsal${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/pkgconfig/ldastoolsal.pc  # [not win]

about:
  home: https://ldastools.docs.ligo.org/LDAS_Tools/Beta/doc/ldas-tools-al/ldastoolsal/html/
  doc_url: https://ldastools.docs.ligo.org/LDAS_Tools/Beta/doc/ldas-tools-al/ldastoolsal/html/
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools abstraction toolkit

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
