travis:
  secure:
    BINSTAR_TOKEN: R9Q9sYu4srxzOmMHLs5ef+541/Osz9TGl6wPOPs6+jIllGURaGgMCiodEuGCHZvxRXYW4hyxep8W46Z+o+h+dReCsDGCcL8nJlzkELyAGX7qXE7FcXIZDMW0HRllfybOjS83vamIK/jwIl4NqvGK2XxBlymJo6giVE+rXu7AcVJFUMeB7sDaXUOxeHA5eoD7w04g4XWyymb+xgqW8dLHmty4pH2OIIPj54xfknhZmxYflGWSq99Gbbwtmp9dy9peg+mlS1tfen+Abn5T6oyRPvQGfbNQfn5VdzQiHo3cE2AIR9iQJ/SWQWPTGLy8sD/XvhMOHdR/ITm/ZiHARTR2q7Jj9RYJxhqpGwd2jK38Ut+f50eahNTlqIKbpY6z39zZHEairS36KmS+M4ovHrmlTRDzfgnDoH1mqCfmg7jF1TRTTi2wVUhRfF8pxDndkrg4GKAriznPj9/t+VqxgOLc1QIVo33N8WFUXFu2M7RG1UlvSFUxjEC5BkBdsjF8I1TzgWaJSAKBG3vg5nwDq68Hdk+LMfBM1za22/ceylC1mVlvvoyRQoSo/opFTssn4r5tenJHDGqIuUzYQpx9FtnGEN4CPZxZHSK39DgTnzXHoUCftfSCL9gjRz41zeB5omWA2SpLEDTdHZr81gBCMJcesVPp8MTAwXewG3hmpFqvrc4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
